import 'dotenv/config'
import * as bcrypt from 'bcryptjs'
import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '../generated/prisma/client'

/**
 * System seed: the reference data the ICS needs to run, plus a small demo set
 * so every endpoint can be exercised end to end.
 *
 * There is no HTTP endpoint yet to create sensitivity levels, categories,
 * action types, org-unit types, attribute definitions, templates or roles, so
 * this file is the single source of that configuration data.
 *
 * Two clearly-marked sections:
 *   1) REFERENCE DATA  — belongs in every environment (prod included).
 *   2) DEMO DATA       — a bootstrap admin, one template and sample attributes
 *                        so you can test the flow. Remove/replace for prod.
 *
 * Idempotent: every write is an upsert keyed on a stable id or unique column,
 * so it is safe to run repeatedly. Runs outside Nest, so dotenv/config loads
 * DATABASE_URL and we use the same pg driver adapter as the app.
 */
const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }),
})

// Bilingual helper: every *.name / *.label column is JSONB { ar, en }.
const t = (ar: string, en: string) => ({ ar, en })

/**
 * Deterministic ids for seeded rows.
 *
 * Primary keys are UUIDs generated by the application (UUIDv7) at runtime, but
 * seeded reference data needs *stable* ids so the seed stays idempotent and so
 * the testing guide and Postman collection can hard-code them. These are valid
 * v7-shaped UUIDs with a zero timestamp, which makes seeded rows instantly
 * recognisable in the database and guarantees they sort before any real row.
 *
 *   00000000-0000-7000-8000-TTTTRRRRRRRR
 *                           |   |
 *                           |   +-- row number within the table
 *                           +------ table number (see SEED_TABLE below)
 */
const seedId = (table: number, row: number): string =>
  `00000000-0000-7000-8000-${table.toString(16).padStart(4, '0')}${row
    .toString(16)
    .padStart(8, '0')}`

const SEED_TABLE = {
  sensitivityLevel: 1,
  requestCategory: 2,
  actionType: 3,
  orgUnitType: 4,
  attributeDefinition: 5,
  permissionGroup: 6,
  permission: 7,
  role: 8,
  user: 9,
  template: 10,
  templateField: 11,
  eligibilityRule: 12,
} as const

const sensitivityId = (n: number) => seedId(SEED_TABLE.sensitivityLevel, n)
const categoryId = (n: number) => seedId(SEED_TABLE.requestCategory, n)
const actionTypeId = (n: number) => seedId(SEED_TABLE.actionType, n)
const unitTypeId = (n: number) => seedId(SEED_TABLE.orgUnitType, n)
const attributeId = (n: number) => seedId(SEED_TABLE.attributeDefinition, n)
const permissionGroupId = (n: number) => seedId(SEED_TABLE.permissionGroup, n)
const permissionId = (n: number) => seedId(SEED_TABLE.permission, n)
const roleId = (n: number) => seedId(SEED_TABLE.role, n)
const userId = (n: number) => seedId(SEED_TABLE.user, n)
const templateId = (n: number) => seedId(SEED_TABLE.template, n)
const templateFieldId = (n: number) => seedId(SEED_TABLE.templateField, n)
const eligibilityRuleId = (n: number) => seedId(SEED_TABLE.eligibilityRule, n)

async function main(): Promise<void> {
  // ==========================================================================
  // 1) REFERENCE DATA
  // ==========================================================================

  // --- Languages (User.preferredLang is a FK to languages.code) -------------
  await prisma.language.upsert({
    where: { code: 'ar' },
    update: {},
    create: {
      code: 'ar',
      name: 'Arabic',
      nativeName: 'العربية',
      isEnabled: true,
      isDefault: true,
    },
  })
  await prisma.language.upsert({
    where: { code: 'en' },
    update: {},
    create: {
      code: 'en',
      name: 'English',
      nativeName: 'English',
      isEnabled: true,
      isDefault: false,
    },
  })

  // --- Request reference-number format --------------------------------------
  await prisma.systemSetting.upsert({
    where: { key: 'request_numbering' },
    update: {},
    create: {
      key: 'request_numbering',
      value: {
        pattern: '{prefix}/{year}/{seq}',
        prefix: 'HIAST',
        seqPadding: 5,
        resetPolicy: 'YEARLY',
        yearDigits: 4,
      },
      description: 'Customizable request reference-number format.',
    },
  })

  // --- Sensitivity levels (rank is unique; higher = more sensitive) ---------
  const sensitivity = [
    { id: sensitivityId(1), rank: 1, name: t('عام', 'Public') },
    { id: sensitivityId(2), rank: 2, name: t('داخلي', 'Internal') },
    { id: sensitivityId(3), rank: 3, name: t('سري', 'Confidential') },
    { id: sensitivityId(4), rank: 4, name: t('سري للغاية', 'Secret') },
  ]
  for (const s of sensitivity) {
    await prisma.sensitivityLevel.upsert({
      where: { rank: s.rank },
      update: {},
      create: { id: s.id, rank: s.rank, name: s.name },
    })
  }

  // --- Request categories ---------------------------------------------------
  const categories = [
    { id: categoryId(1), name: t('إداري', 'Administrative') },
    { id: categoryId(2), name: t('أكاديمي', 'Academic') },
    { id: categoryId(3), name: t('مالي', 'Financial') },
  ]
  for (const c of categories) {
    await prisma.requestCategory.upsert({
      where: { id: c.id },
      update: {},
      create: { id: c.id, name: c.name },
    })
  }

  // --- Action types (isTerminal ends the request) ---------------------------
  const actionTypes = [
    { id: actionTypeId(1), code: 'APPROVE', name: t('موافقة', 'Approve'), isTerminal: true },
    { id: actionTypeId(2), code: 'REJECT', name: t('رفض', 'Reject'), isTerminal: true },
    { id: actionTypeId(3), code: 'FORWARD', name: t('إحالة', 'Forward'), isTerminal: false },
    { id: actionTypeId(4), code: 'RETURN', name: t('إعادة', 'Return'), isTerminal: false },
    { id: actionTypeId(5), code: 'SIGN', name: t('توقيع', 'Sign'), isTerminal: false },
    {
      id: actionTypeId(6),
      code: 'REQUEST_PAYMENT',
      name: t('طلب دفع', 'Request payment'),
      isTerminal: false,
    },
    {
      id: actionTypeId(7),
      code: 'CONFIRM_PAYMENT',
      name: t('تأكيد دفع', 'Confirm payment'),
      isTerminal: false,
    },
  ]
  for (const a of actionTypes) {
    await prisma.actionType.upsert({
      where: { code: a.code },
      update: {},
      create: { id: a.id, code: a.code, name: a.name, isTerminal: a.isTerminal },
    })
  }

  // --- Org-unit types -------------------------------------------------------
  const unitTypes = [
    { id: unitTypeId(1), code: 'UNIVERSITY', name: t('جامعة', 'University') },
    { id: unitTypeId(2), code: 'FACULTY', name: t('كلية', 'Faculty') },
    { id: unitTypeId(3), code: 'DEPARTMENT', name: t('قسم', 'Department') },
    { id: unitTypeId(4), code: 'UNIT', name: t('وحدة', 'Unit') },
    { id: unitTypeId(5), code: 'OFFICE', name: t('مكتب', 'Office') },
  ]
  for (const u of unitTypes) {
    await prisma.orgUnitType.upsert({
      where: { code: u.code },
      update: {},
      create: { id: u.id, code: u.code, name: u.name },
    })
  }

  // --- ABAC attribute vocabulary --------------------------------------------
  const attributes = [
    { id: attributeId(1), code: 'user_type', label: t('نوع المستخدم', 'User type'), dataType: 'TEXT' },
    { id: attributeId(2), code: 'degree_level', label: t('المرحلة الدراسية', 'Degree level'), dataType: 'ENUM' },
    { id: attributeId(3), code: 'gpa', label: t('المعدل التراكمي', 'GPA'), dataType: 'NUMBER' },
    { id: attributeId(4), code: 'clearance_level', label: t('مستوى التصريح', 'Clearance level'), dataType: 'NUMBER' },
  ]
  for (const a of attributes) {
    await prisma.attributeDefinition.upsert({
      where: { code: a.code },
      update: {},
      create: { id: a.id, code: a.code, label: a.label, dataType: a.dataType },
    })
  }

  // --- RBAC: permission group, permissions, role ----------------------------
  const group = await prisma.permissionGroup.upsert({
    where: { id: permissionGroupId(1) },
    update: {},
    create: {
      id: permissionGroupId(1),
      name: t('إدارة الوصول', 'Access Management'),
    },
  })

  const permissions = [
    { id: permissionId(1), code: 'user.manage', name: t('إدارة المستخدمين', 'Manage users') },
    { id: permissionId(2), code: 'request.read', name: t('قراءة الطلبات', 'Read requests') },
    { id: permissionId(3), code: 'request.act', name: t('التصرف بالطلبات', 'Act on requests') },
    { id: permissionId(4), code: 'workflow.manage', name: t('إدارة مسارات العمل', 'Manage workflows') },
    { id: permissionId(5), code: 'template.manage', name: t('إدارة القوالب', 'Manage templates') },
    { id: permissionId(6), code: 'reports.view', name: t('عرض التقارير', 'View reports') },
  ]
  for (const p of permissions) {
    await prisma.permission.upsert({
      where: { code: p.code },
      update: {},
      create: { id: p.id, groupId: group.id, code: p.code, name: p.name },
    })
  }

  const role = await prisma.role.upsert({
    where: { id: roleId(1) },
    update: {},
    create: {
      id: roleId(1),
      name: t('مدير النظام', 'Administrator'),
      isSystem: true,
    },
  })

  // Administrator carries every permission above.
  for (const p of permissions) {
    await prisma.rolePermission.upsert({
      where: { roleId_permissionId: { roleId: role.id, permissionId: p.id } },
      update: {},
      create: { roleId: role.id, permissionId: p.id },
    })
  }

  // ==========================================================================
  // 2) DEMO DATA (replace for production)
  // ==========================================================================

  // --- Bootstrap admin you can log in as ------------------------------------
  // Email:    admin@correspondence.local
  // Password: Admin@12345      <-- change this after first login
  const passwordHash = await bcrypt.hash('Admin@12345', 10)
  const user = await prisma.user.upsert({
    where: { email: 'admin@correspondence.local' },
    update: { passwordHash },
    create: {
      id: userId(1),
      userType: 'ADMIN',
      fullNameAr: 'مدير النظام',
      fullNameEn: 'System Administrator',
      institutionalNumber: 'STF-0001',
      email: 'admin@correspondence.local',
      passwordHash,
      authProvider: 'LOCAL',
      preferredLang: 'ar',
      status: 'ACTIVE',
    },
  })

  // Admin -> Administrator role. The compound unique includes assignedAt +
  // nullable departmentId, so clear-then-create instead of upsert.
  await prisma.userRole.deleteMany({ where: { userId: user.id, roleId: role.id } })
  await prisma.userRole.create({ data: { userId: user.id, roleId: role.id } })

  // --- Reviewer role + two staff reviewers (to test the ownership rule) ------
  // A Reviewer can read and act on requests, but cannot manage config. These
  // two users prove that request.act alone is not enough: you can only act on
  // a step that is assigned to you. In the walkthrough reviewer1 is assigned
  // the step and succeeds; reviewer2 has the same permission but is blocked 403.
  const reviewerRole = await prisma.role.upsert({
    where: { id: roleId(2) },
    update: {},
    create: {
      id: roleId(2),
      name: t('مُراجِع', 'Reviewer'),
      isSystem: false,
    },
  })
  for (const id of [permissionId(2), permissionId(3)]) {
    // request.read (2) + request.act (3)
    await prisma.rolePermission.upsert({
      where: {
        roleId_permissionId: {
          roleId: reviewerRole.id,
          permissionId: id,
        },
      },
      update: {},
      create: { roleId: reviewerRole.id, permissionId: id },
    })
  }

  const reviewerPasswordHash = await bcrypt.hash('Review@12345', 10)
  const reviewers = [
    {
      id: userId(2),
      fullNameAr: 'المراجع الأول',
      fullNameEn: 'Reviewer One',
      institutionalNumber: 'STF-0002',
      email: 'reviewer1@correspondence.local',
    },
    {
      id: userId(3),
      fullNameAr: 'المراجع الثاني',
      fullNameEn: 'Reviewer Two',
      institutionalNumber: 'STF-0003',
      email: 'reviewer2@correspondence.local',
    },
  ]
  for (const r of reviewers) {
    const reviewer = await prisma.user.upsert({
      where: { email: r.email },
      update: { passwordHash: reviewerPasswordHash },
      create: {
        id: r.id,
        userType: 'EMPLOYEE',
        fullNameAr: r.fullNameAr,
        fullNameEn: r.fullNameEn,
        institutionalNumber: r.institutionalNumber,
        email: r.email,
        passwordHash: reviewerPasswordHash,
        authProvider: 'LOCAL',
        preferredLang: 'ar',
        status: 'ACTIVE',
      },
    })
    await prisma.userRole.deleteMany({
      where: { userId: reviewer.id, roleId: reviewerRole.id },
    })
    await prisma.userRole.create({
      data: { userId: reviewer.id, roleId: reviewerRole.id },
    })
  }

  // --- Sample attribute values for the admin (so ABAC returns eligible) -----
  const userAttrValues = [
    { attributeId: attributeId(1), value: 'EMPLOYEE' },
    { attributeId: attributeId(4), value: 3 },
  ]
  for (const ua of userAttrValues) {
    await prisma.userAttribute.upsert({
      where: {
        userId_attributeId: { userId: user.id, attributeId: ua.attributeId },
      },
      update: { value: ua.value },
      create: { userId: user.id, attributeId: ua.attributeId, value: ua.value },
    })
  }

  // --- One demo template (Academic, Internal) with fields + eligibility -----
  await prisma.template.upsert({
    where: { id: templateId(1) },
    update: {},
    create: {
      id: templateId(1),
      categoryId: categoryId(2), // Academic
      sensitivityLevelId: sensitivityId(2), // Internal
      title: t('طلب شهادة عدم ممانعة', 'No-objection certificate request'),
      isActive: true,
    },
  })

  const fields = [
    {
      id: templateFieldId(1),
      fieldKey: 'reason',
      label: t('السبب', 'Reason'),
      dataType: 'TEXT',
      isRequired: true,
      ordinal: 1,
    },
    {
      id: templateFieldId(2),
      fieldKey: 'destination',
      label: t('الجهة', 'Destination'),
      dataType: 'TEXT',
      isRequired: false,
      ordinal: 2,
    },
  ]
  for (const f of fields) {
    await prisma.templateField.upsert({
      where: {
        templateId_fieldKey: { templateId: templateId(1), fieldKey: f.fieldKey },
      },
      update: {},
      create: {
        id: f.id,
        templateId: templateId(1),
        fieldKey: f.fieldKey,
        label: f.label,
        dataType: f.dataType,
        isRequired: f.isRequired,
        ordinal: f.ordinal,
      },
    })
  }

  // Eligible only if user_type == EMPLOYEE AND clearance_level >= 2.
  const rules = [
    {
      id: eligibilityRuleId(1),
      attributeId: attributeId(1),
      operator: 'EQ',
      value: 'EMPLOYEE',
      description: t('الموظفون فقط', 'Employees only'),
    },
    {
      id: eligibilityRuleId(2),
      attributeId: attributeId(4),
      operator: 'GTE',
      value: 2,
      description: t('مستوى التصريح 2 على الأقل', 'Clearance level 2 or higher'),
    },
  ]
  for (const r of rules) {
    await prisma.templateEligibilityRule.upsert({
      where: { id: r.id },
      update: {},
      create: {
        id: r.id,
        templateId: templateId(1),
        attributeId: r.attributeId,
        operator: r.operator,
        value: r.value,
        description: r.description,
      },
    })
  }

  console.log('Seed complete.')
  console.log('  Admin login  : admin@correspondence.local / Admin@12345')
  console.log('  Reviewer 1   : reviewer1@correspondence.local / Review@12345')
  console.log('  Reviewer 2   : reviewer2@correspondence.local / Review@12345')
  console.log('')
  console.log('  Seeded ids (stable across resets):')
  console.log(`    admin user     : ${userId(1)}`)
  console.log(`    reviewer 1     : ${userId(2)}`)
  console.log(`    reviewer 2     : ${userId(3)}`)
  console.log(`    Reviewer role  : ${roleId(2)}`)
  console.log(`    demo template  : ${templateId(1)}`)
  console.log(`    action APPROVE : ${actionTypeId(1)}`)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (error) => {
    console.error(error)
    await prisma.$disconnect()
    process.exit(1)
  })
