import 'dotenv/config'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import * as bcrypt from 'bcryptjs'
import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '../generated/prisma/client'
import {
  SYSTEM_USER_EMAIL,
  SYSTEM_USER_ID,
} from '../src/infrastructure/shared/system-actor'

/**
 * System seed: the reference data the ICS needs to run, plus a small demo set
 * so every endpoint can be exercised end to end.
 *
 * There is no HTTP endpoint yet to create sensitivity levels, categories,
 * action types, org-unit types, attribute definitions, templates or roles, so
 * this file is the single source of that configuration data.
 *
 * Two clearly-marked sections:
 *   1) REFERENCE DATA  — belongs in every environment (prod included).
 *   2) DEMO DATA       — a bootstrap admin, one template and sample attributes
 *                        so you can test the flow. Remove/replace for prod.
 *
 * Idempotent: every write is an upsert keyed on a stable id or unique column,
 * so it is safe to run repeatedly. Runs outside Nest, so dotenv/config loads
 * DATABASE_URL and we use the same pg driver adapter as the app.
 */
const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }),
})

// Bilingual helper: every *.name / *.label column is JSONB { ar, en }.
const t = (ar: string, en: string) => ({ ar, en })

/**
 * Deterministic ids for seeded rows.
 *
 * Primary keys are UUIDs generated by the application (UUIDv7) at runtime, but
 * seeded reference data needs *stable* ids so the seed stays idempotent and so
 * the testing guide and Postman collection can hard-code them. These are valid
 * v7-shaped UUIDs with a zero timestamp, which makes seeded rows instantly
 * recognisable in the database and guarantees they sort before any real row.
 *
 *   00000000-0000-7000-8000-TTTTRRRRRRRR
 *                           |   |
 *                           |   +-- row number within the table
 *                           +------ table number (see SEED_TABLE below)
 */
const seedId = (table: number, row: number): string =>
  `00000000-0000-7000-8000-${table.toString(16).padStart(4, '0')}${row
    .toString(16)
    .padStart(8, '0')}`

const SEED_TABLE = {
  sensitivityLevel: 1,
  requestCategory: 2,
  actionType: 3,
  orgUnitType: 4,
  attributeDefinition: 5,
  permissionGroup: 6,
  permission: 7,
  role: 8,
  user: 9,
  template: 10,
  templateField: 11,
  eligibilityRule: 12,
  workflowPath: 13,
  workflowStep: 14,
  systemSetting: 15,
} as const

const sensitivityId = (n: number) => seedId(SEED_TABLE.sensitivityLevel, n)
const categoryId = (n: number) => seedId(SEED_TABLE.requestCategory, n)
const actionTypeId = (n: number) => seedId(SEED_TABLE.actionType, n)
const unitTypeId = (n: number) => seedId(SEED_TABLE.orgUnitType, n)
const attributeId = (n: number) => seedId(SEED_TABLE.attributeDefinition, n)
const permissionGroupId = (n: number) => seedId(SEED_TABLE.permissionGroup, n)
const permissionId = (n: number) => seedId(SEED_TABLE.permission, n)
const roleId = (n: number) => seedId(SEED_TABLE.role, n)
const userId = (n: number) => seedId(SEED_TABLE.user, n)
const templateId = (n: number) => seedId(SEED_TABLE.template, n)
const templateFieldId = (n: number) => seedId(SEED_TABLE.templateField, n)
const eligibilityRuleId = (n: number) => seedId(SEED_TABLE.eligibilityRule, n)
const workflowPathId = (n: number) => seedId(SEED_TABLE.workflowPath, n)
const workflowStepId = (n: number) => seedId(SEED_TABLE.workflowStep, n)

/**
 * The 12 templates the AI models were trained against, exported from the
 * training repository. Two of the columns in it are model inputs rather than
 * text for people -- `classifierDocument` is the exact string the classifier
 * embeds, and each field's `extractionQuestion` is the exact question the
 * extractor is asked. They are seeded verbatim: reword either one and the
 * measured accuracy stops describing the running system.
 */
interface CatalogueField {
  key: string
  labelAr: string
  labelEn: string | null
  type: 'TEXT' | 'NUMBER' | 'DATE' | 'BOOLEAN' | 'ENUM'
  required: boolean
  options: { code: string; labelAr: string }[] | null
  extractionQuestion: string | null
}

interface CatalogueTemplate {
  code: string
  nameAr: string
  nameEn: string
  descriptionAr: string
  requesterType: 'STUDENT' | 'EMPLOYEE'
  classifierDocument: string
  fields: CatalogueField[]
}

const loadCatalogue = (): CatalogueTemplate[] => {
  const path = join(__dirname, 'seed-data', 'template-catalogue.json')
  return JSON.parse(readFileSync(path, 'utf8')) as CatalogueTemplate[]
}

async function main(): Promise<void> {
  // ==========================================================================
  // 1) REFERENCE DATA
  // ==========================================================================

  // --- Languages (User.preferredLang is a FK to languages.code) -------------
  await prisma.language.upsert({
    where: { code: 'ar' },
    update: {},
    create: {
      code: 'ar',
      name: 'Arabic',
      nativeName: 'العربية',
      isEnabled: true,
      isDefault: true,
    },
  })
  await prisma.language.upsert({
    where: { code: 'en' },
    update: {},
    create: {
      code: 'en',
      name: 'English',
      nativeName: 'English',
      isEnabled: true,
      isDefault: false,
    },
  })

  // --- Request reference-number format --------------------------------------
  await prisma.systemSetting.upsert({
    where: { key: 'request_numbering' },
    update: {},
    create: {
      key: 'request_numbering',
      value: {
        pattern: '{prefix}/{year}/{seq}',
        prefix: 'HIAST',
        seqPadding: 5,
        resetPolicy: 'YEARLY',
        yearDigits: 4,
      },
      description: 'Customizable request reference-number format.',
    },
  })

  // --- SLA risk thresholds --------------------------------------------------
  // atRiskHours is measured in *working* hours remaining, not clock hours, so
  // a deadline on the far side of a weekend does not raise a flag early.
  await prisma.systemSetting.upsert({
    where: { key: 'sla_thresholds' },
    update: {},
    create: {
      key: 'sla_thresholds',
      value: { atRiskHours: 8 },
      description:
        'Working hours of remaining time below which a step counts as at risk.',
    },
  })

  // --- Working-hours policy -------------------------------------------------
  // Seeded *disabled*, so the API can be exercised at any hour. The real
  // schedule is stored alongside the flag rather than deleted, so switching the
  // control back on is a one-word edit and the guard can still be demonstrated.
  //
  // Without this row the service falls back to its built-in default, which is
  // enabled -- so the row has to exist to turn the guard off, and this is the
  // only reason the setting is seeded at all.
  await prisma.systemSetting.upsert({
    where: { key: 'working_hours' },
    update: {},
    create: {
      id: seedId(SEED_TABLE.systemSetting, 1),
      key: 'working_hours',
      value: {
        enabled: false,
        days: [0, 1, 2, 3, 4],
        start: '08:00',
        end: '15:30',
        timezone: 'Asia/Damascus',
      },
      description:
        'Weekly working-hours policy. days uses 0=Sunday; times are wall-clock in timezone. enabled=false lifts the working-hours restriction on staff actions.',
    },
  })

  // --- Sensitivity levels (rank is unique; higher = more sensitive) ---------
  const sensitivity = [
    { id: sensitivityId(1), rank: 1, name: t('عام', 'Public') },
    { id: sensitivityId(2), rank: 2, name: t('داخلي', 'Internal') },
    { id: sensitivityId(3), rank: 3, name: t('سري', 'Confidential') },
    { id: sensitivityId(4), rank: 4, name: t('سري للغاية', 'Secret') },
  ]
  for (const s of sensitivity) {
    await prisma.sensitivityLevel.upsert({
      where: { rank: s.rank },
      update: {},
      create: { id: s.id, rank: s.rank, name: s.name },
    })
  }

  // --- Request categories ---------------------------------------------------
  const categories = [
    { id: categoryId(1), name: t('إداري', 'Administrative') },
    { id: categoryId(2), name: t('أكاديمي', 'Academic') },
    { id: categoryId(3), name: t('مالي', 'Financial') },
  ]
  for (const c of categories) {
    await prisma.requestCategory.upsert({
      where: { id: c.id },
      update: {},
      create: { id: c.id, name: c.name },
    })
  }

  // --- Action types (isTerminal ends the request) ---------------------------
  const actionTypes = [
    { id: actionTypeId(1), code: 'APPROVE', name: t('موافقة', 'Approve'), isTerminal: true },
    { id: actionTypeId(2), code: 'REJECT', name: t('رفض', 'Reject'), isTerminal: true },
    { id: actionTypeId(3), code: 'FORWARD', name: t('إحالة', 'Forward'), isTerminal: false },
    { id: actionTypeId(4), code: 'RETURN', name: t('إعادة', 'Return'), isTerminal: false },
    { id: actionTypeId(5), code: 'SIGN', name: t('توقيع', 'Sign'), isTerminal: false },
    {
      id: actionTypeId(6),
      code: 'REQUEST_PAYMENT',
      name: t('طلب دفع', 'Request payment'),
      isTerminal: false,
    },
    {
      id: actionTypeId(7),
      code: 'CONFIRM_PAYMENT',
      name: t('تأكيد دفع', 'Confirm payment'),
      isTerminal: false,
    },
    // How a re-prioritisation files itself. Not a step decision like the
    // others, but it belongs in the same trail: it is the row that says who
    // moved a request up the queue and why.
    // A waiver is not a confirmation and must not be filed as one: CONFIRM_PAYMENT
    // on a row where nothing was paid is exactly the kind of trail that makes an
    // audit distrust everything around it.
    {
      id: actionTypeId(9),
      code: 'WAIVE_PAYMENT',
      name: t('إعفاء من الرسم', 'Waive fee'),
      isTerminal: false,
    },
    {
      id: actionTypeId(8),
      code: 'CHANGE_PRIORITY',
      name: t('تغيير الأولوية', 'Change priority'),
      isTerminal: false,
    },
  ]
  for (const a of actionTypes) {
    await prisma.actionType.upsert({
      where: { code: a.code },
      update: {},
      create: { id: a.id, code: a.code, name: a.name, isTerminal: a.isTerminal },
    })
  }

  // --- Org-unit types -------------------------------------------------------
  const unitTypes = [
    { id: unitTypeId(1), code: 'UNIVERSITY', name: t('جامعة', 'University') },
    { id: unitTypeId(2), code: 'FACULTY', name: t('كلية', 'Faculty') },
    { id: unitTypeId(3), code: 'DEPARTMENT', name: t('قسم', 'Department') },
    { id: unitTypeId(4), code: 'UNIT', name: t('وحدة', 'Unit') },
    { id: unitTypeId(5), code: 'OFFICE', name: t('مكتب', 'Office') },
  ]
  for (const u of unitTypes) {
    await prisma.orgUnitType.upsert({
      where: { code: u.code },
      update: {},
      create: { id: u.id, code: u.code, name: u.name },
    })
  }

  // --- ABAC attribute vocabulary --------------------------------------------
  const attributes = [
    { id: attributeId(1), code: 'user_type', label: t('نوع المستخدم', 'User type'), dataType: 'TEXT' },
    { id: attributeId(2), code: 'degree_level', label: t('المرحلة الدراسية', 'Degree level'), dataType: 'ENUM' },
    { id: attributeId(3), code: 'gpa', label: t('المعدل التراكمي', 'GPA'), dataType: 'NUMBER' },
    { id: attributeId(4), code: 'clearance_level', label: t('مستوى التصريح', 'Clearance level'), dataType: 'NUMBER' },
  ]
  for (const a of attributes) {
    await prisma.attributeDefinition.upsert({
      where: { code: a.code },
      update: {},
      create: { id: a.id, code: a.code, label: a.label, dataType: a.dataType },
    })
  }

  // --- RBAC: permission group, permissions, role ----------------------------
  const group = await prisma.permissionGroup.upsert({
    where: { id: permissionGroupId(1) },
    update: {},
    create: {
      id: permissionGroupId(1),
      name: t('إدارة الوصول', 'Access Management'),
      description: t(
        'الصلاحيات التي تحدد ما يمكن لكل دور فعله في النظام.',
        'Permissions that decide what each role is allowed to do.',
      ),
    },
  })

  const permissions = [
    { id: permissionId(1), code: 'user.manage', name: t('إدارة المستخدمين', 'Manage users') },
    { id: permissionId(2), code: 'request.read', name: t('قراءة الطلبات', 'Read requests') },
    { id: permissionId(3), code: 'request.act', name: t('التصرف بالطلبات', 'Act on requests') },
    { id: permissionId(4), code: 'workflow.manage', name: t('إدارة مسارات العمل', 'Manage workflows') },
    { id: permissionId(5), code: 'template.manage', name: t('إدارة القوالب', 'Manage templates') },
    { id: permissionId(6), code: 'reports.view', name: t('عرض التقارير', 'View reports') },
    { id: permissionId(7), code: 'request.classify', name: t('تصنيف الطلبات', 'Classify requests') },
    // Guards /health/detailed and the maintenance routes. Those routes already
    // declared this permission, but nothing created it -- and a permission no
    // row exists for is one nobody can hold, so the guard was refusing every
    // caller including the administrator, with no way to grant it.
    { id: permissionId(8), code: 'system.monitor', name: t('مراقبة النظام', 'Monitor the system') },
    // Guards /roles: composing roles and deciding what each one grants. Kept
    // separate from user.manage because only this one can escalate its own
    // holder -- whoever can edit role_permissions can grant themselves
    // everything. The Administrator role below receives it with the rest.
    { id: permissionId(9), code: 'role.manage', name: t('إدارة الأدوار', 'Manage roles') },
    // Settling a fee is money changing hands, so it is deliberately NOT part
    // of request.act. A reviewer who works the queue can start and complete
    // steps; confirming that a fee was paid, or waiving it outright, is a
    // separate duty and needs this permission. Granted below to the
    // Administrator role only -- add it to another role to delegate it.
    { id: permissionId(10), code: 'payment.settle', name: t('تسوية الرسوم', 'Settle fees') },
  ]

  /*
   * permissions.description has existed as a nullable JSONB column since the
   * first migration and nothing ever wrote it, so every row read NULL. The
   * role-management screen reads this text straight from the role query, and an
   * administrator deciding whether to grant 'request.act' deserves a sentence
   * rather than a dotted code. Keyed by code so the text survives re-seeding.
   */
  const permissionDescriptions: Record<string, { ar: string; en: string }> = {
    'user.manage': {
      ar: 'إنشاء المستخدمين وتعديل بياناتهم وتعطيلهم، وإدارة الوحدات التنظيمية.',
      en: 'Create, edit and deactivate users, and manage organizational units.',
    },
    'request.read': {
      ar: 'عرض الطلبات وقوائم العمل وتفاصيل الطلب دون إمكانية التصرف بها.',
      en: 'View requests, work queues and request details, without acting on them.',
    },
    'request.act': {
      ar: 'بدء خطوات الطلب وإكمالها ورفضها وتخصيصها، وتغيير أولوية الطلب.',
      en: 'Start, complete, reject and assign request steps, and change a request priority.',
    },
    'workflow.manage': {
      ar: 'تعريف مسارات العمل وخطواتها والمسؤولين عنها ومهل الإنجاز.',
      en: 'Define workflow paths, their steps, assignees and SLA targets.',
    },
    'template.manage': {
      ar: 'إنشاء قوالب الطلبات وحقولها وشروط الأهلية وتعديلها.',
      en: 'Create and edit request templates, their fields and eligibility rules.',
    },
    'reports.view': {
      ar: 'عرض التقارير ولوحات المؤشرات وتصديرها.',
      en: 'View and export reports and indicator dashboards.',
    },
    'request.classify': {
      ar: 'تصنيف الطلبات المحوَّلة للمراجعة البشرية وتعبئة حقولها المستخرجة.',
      en: 'Classify requests routed to human review and fill their extracted fields.',
    },
    'system.monitor': {
      ar: 'الاطلاع على صحة النظام التفصيلية وتشغيل مهام الصيانة.',
      en: 'Inspect detailed system health and run maintenance jobs.',
    },
    'role.manage': {
      ar: 'إنشاء الأدوار وتحديد صلاحياتها ومنحها للمستخدمين. صلاحية حساسة: من يملكها يستطيع منح نفسه أي صلاحية أخرى.',
      en: 'Create roles, decide what they grant, and assign them. Sensitive: whoever holds it can grant themselves anything else.',
    },
    'payment.settle': {
      ar: 'تأكيد دفع رسوم الطلب أو الإعفاء منها مع تسجيل السبب.',
      en: 'Confirm that a request fee was paid, or waive it with a recorded reason.',
    },
  }

  for (const p of permissions) {
    const described = permissionDescriptions[p.code]
    const description = described ? t(described.ar, described.en) : undefined
    await prisma.permission.upsert({
      where: { code: p.code },
      // Descriptions ARE refreshed on re-seed: they are documentation, and
      // stale documentation about who may take money is worse than none.
      update: description ? { description } : {},
      create: {
        id: p.id,
        groupId: group.id,
        code: p.code,
        name: p.name,
        ...(description ? { description } : {}),
      },
    })
  }

  const role = await prisma.role.upsert({
    where: { id: roleId(1) },
    update: {},
    create: {
      id: roleId(1),
      name: t('مدير النظام', 'Administrator'),
      isSystem: true,
    },
  })

  // Administrator carries every permission above.
  for (const p of permissions) {
    await prisma.rolePermission.upsert({
      where: { roleId_permissionId: { roleId: role.id, permissionId: p.id } },
      update: {},
      create: { roleId: role.id, permissionId: p.id },
    })
  }

  // ==========================================================================
  // 2) DEMO DATA (replace for production)
  // ==========================================================================

  // --- SYSTEM account (reference data, not demo data) -----------------------
  // Background jobs and the seed itself write rows too. Without an account of
  // their own, those rows carry an empty created_by / updated_by and the audit
  // trail cannot tell "nobody recorded it" apart from "the system did it".
  // Nobody can sign in as this account: it has no password hash and its status
  // is INACTIVE, both of which the local auth provider rejects.
  await prisma.user.upsert({
    where: { id: SYSTEM_USER_ID },
    update: { status: 'INACTIVE', passwordHash: null },
    create: {
      id: SYSTEM_USER_ID,
      userType: 'ADMIN',
      fullNameAr: 'النظام',
      fullNameEn: 'System',
      email: SYSTEM_USER_EMAIL,
      authProvider: 'SYSTEM',
      preferredLang: 'ar',
      status: 'INACTIVE',
    },
  })

  // --- Bootstrap admin you can log in as ------------------------------------
  // Email:    admin@correspondence.local
  // Password: Admin@12345      <-- change this after first login
  const passwordHash = await bcrypt.hash('Admin@12345', 10)
  const user = await prisma.user.upsert({
    where: { email: 'admin@correspondence.local' },
    update: { passwordHash },
    create: {
      id: userId(1),
      userType: 'ADMIN',
      fullNameAr: 'مدير النظام',
      fullNameEn: 'System Administrator',
      institutionalNumber: 'STF-0001',
      email: 'admin@correspondence.local',
      passwordHash,
      authProvider: 'LOCAL',
      preferredLang: 'ar',
      status: 'ACTIVE',
    },
  })

  // Admin -> Administrator role. The compound unique includes assignedAt +
  // nullable departmentId, so clear-then-create instead of upsert.
  await prisma.userRole.deleteMany({ where: { userId: user.id, roleId: role.id } })
  await prisma.userRole.create({ data: { userId: user.id, roleId: role.id } })

  // --- Reviewer role + two staff reviewers (to test the ownership rule) ------
  // A Reviewer can read and act on requests, but cannot manage config. These
  // two users prove that request.act alone is not enough: you can only act on
  // a step that is assigned to you. In the walkthrough reviewer1 is assigned
  // the step and succeeds; reviewer2 has the same permission but is blocked 403.
  const reviewerRole = await prisma.role.upsert({
    where: { id: roleId(2) },
    update: {},
    create: {
      id: roleId(2),
      name: t('مُراجِع', 'Reviewer'),
      isSystem: false,
    },
  })
  for (const id of [permissionId(2), permissionId(3)]) {
    // request.read (2) + request.act (3)
    await prisma.rolePermission.upsert({
      where: {
        roleId_permissionId: {
          roleId: reviewerRole.id,
          permissionId: id,
        },
      },
      update: {},
      create: { roleId: reviewerRole.id, permissionId: id },
    })
  }

  const reviewerPasswordHash = await bcrypt.hash('Review@12345', 10)
  const reviewers = [
    {
      id: userId(2),
      fullNameAr: 'المراجع الأول',
      fullNameEn: 'Reviewer One',
      institutionalNumber: 'STF-0002',
      email: 'reviewer1@correspondence.local',
    },
    {
      id: userId(3),
      fullNameAr: 'المراجع الثاني',
      fullNameEn: 'Reviewer Two',
      institutionalNumber: 'STF-0003',
      email: 'reviewer2@correspondence.local',
    },
  ]
  for (const r of reviewers) {
    const reviewer = await prisma.user.upsert({
      where: { email: r.email },
      update: { passwordHash: reviewerPasswordHash },
      create: {
        id: r.id,
        userType: 'EMPLOYEE',
        fullNameAr: r.fullNameAr,
        fullNameEn: r.fullNameEn,
        institutionalNumber: r.institutionalNumber,
        email: r.email,
        passwordHash: reviewerPasswordHash,
        authProvider: 'LOCAL',
        preferredLang: 'ar',
        status: 'ACTIVE',
      },
    })
    await prisma.userRole.deleteMany({
      where: { userId: reviewer.id, roleId: reviewerRole.id },
    })
    await prisma.userRole.create({
      data: { userId: reviewer.id, roleId: reviewerRole.id },
    })
  }

  // --- Classification Reviewer role -----------------------------------------
  // Classifying a request is now its own permission (request.classify) rather
  // than part of request.act. That separates two different duties: deciding
  // which template -- and therefore which workflow -- a request follows, versus
  // approving a step inside that workflow. This role holds the first without
  // the second. reviewer1 gets it in addition to Reviewer so the
  // human-in-the-loop queue is testable straight after seeding.
  const classifierRole = await prisma.role.upsert({
    where: { id: roleId(3) },
    update: {},
    create: {
      id: roleId(3),
      name: t('مصنّف الطلبات', 'Classification Reviewer'),
      isSystem: false,
    },
  })
  for (const id of [permissionId(2), permissionId(7)]) {
    // request.read (2) + request.classify (7)
    await prisma.rolePermission.upsert({
      where: {
        roleId_permissionId: { roleId: classifierRole.id, permissionId: id },
      },
      update: {},
      create: { roleId: classifierRole.id, permissionId: id },
    })
  }
  await prisma.userRole.deleteMany({
    where: { userId: userId(2), roleId: classifierRole.id },
  })
  await prisma.userRole.create({
    data: { userId: userId(2), roleId: classifierRole.id },
  })

  // --- Sample attribute values for the admin (so ABAC returns eligible) -----
  const userAttrValues = [
    { attributeId: attributeId(1), value: 'ADMIN' },
    { attributeId: attributeId(4), value: 3 },
  ]
  for (const ua of userAttrValues) {
    await prisma.userAttribute.upsert({
      where: {
        userId_attributeId: { userId: user.id, attributeId: ua.attributeId },
      },
      update: { value: ua.value },
      create: { userId: user.id, attributeId: ua.attributeId, value: ua.value },
    })
  }

  // --- The AI service's own account -----------------------------------------
  // The classifier is a client like any other: it signs in, and it is limited
  // to what it needs -- read requests, and say which template one matches. It
  // deliberately holds neither request.act nor template.manage, so a mistake
  // (or a stolen token) cannot approve a request or rewrite the catalogue.
  const aiRole = await prisma.role.upsert({
    where: { id: roleId(4) },
    update: {},
    create: {
      id: roleId(4),
      name: t('خدمة الذكاء الاصطناعي', 'AI Service'),
      isSystem: true,
    },
  })
  for (const id of [permissionId(2), permissionId(7)]) {
    // request.read (2) + request.classify (7)
    await prisma.rolePermission.upsert({
      where: { roleId_permissionId: { roleId: aiRole.id, permissionId: id } },
      update: {},
      create: { roleId: aiRole.id, permissionId: id },
    })
  }

  // Password matches AI_SERVICE_PASSWORD in ai-service/.env. Change both
  // together before this leaves a development machine.
  const aiPasswordHash = await bcrypt.hash('change-me', 10)
  const aiUser = await prisma.user.upsert({
    where: { email: 'ai-service@correspondence.local' },
    update: { passwordHash: aiPasswordHash },
    create: {
      id: userId(4),
      userType: 'EMPLOYEE',
      fullNameAr: 'خدمة التصنيف الآلي',
      fullNameEn: 'AI Classification Service',
      institutionalNumber: 'STF-0004',
      email: 'ai-service@correspondence.local',
      passwordHash: aiPasswordHash,
      authProvider: 'LOCAL',
      preferredLang: 'ar',
      status: 'ACTIVE',
    },
  })
  await prisma.userRole.deleteMany({
    where: { userId: aiUser.id, roleId: aiRole.id },
  })
  await prisma.userRole.create({
    data: { userId: aiUser.id, roleId: aiRole.id },
  })

  // --- One demo template (Academic, Internal) with fields + eligibility -----
  await prisma.template.upsert({
    where: { id: templateId(1) },
    update: {},
    create: {
      id: templateId(1),
      categoryId: categoryId(2), // Academic
      sensitivityLevelId: sensitivityId(2), // Internal
      title: t('طلب شهادة عدم ممانعة', 'No-objection certificate request'),
      isActive: true,
    },
  })

  const fields = [
    {
      id: templateFieldId(1),
      fieldKey: 'reason',
      label: t('السبب', 'Reason'),
      dataType: 'TEXT',
      isRequired: true,
      ordinal: 1,
    },
    {
      id: templateFieldId(2),
      fieldKey: 'destination',
      label: t('الجهة', 'Destination'),
      dataType: 'TEXT',
      isRequired: false,
      ordinal: 2,
    },
  ]
  for (const f of fields) {
    await prisma.templateField.upsert({
      where: {
        templateId_fieldKey: { templateId: templateId(1), fieldKey: f.fieldKey },
      },
      update: {},
      create: {
        id: f.id,
        templateId: templateId(1),
        fieldKey: f.fieldKey,
        label: f.label,
        dataType: f.dataType,
        isRequired: f.isRequired,
        ordinal: f.ordinal,
      },
    })
  }

  // Eligible only if user_type is EMPLOYEE or ADMIN, AND clearance_level >= 2.
  const rules = [
    {
      id: eligibilityRuleId(1),
      attributeId: attributeId(1),
      operator: 'IN',
      value: ['EMPLOYEE', 'ADMIN'],
      description: t('الموظفون والإداريون', 'Employees and administrators'),
    },
    {
      id: eligibilityRuleId(2),
      attributeId: attributeId(4),
      operator: 'GTE',
      value: 2,
      description: t('مستوى التصريح 2 على الأقل', 'Clearance level 2 or higher'),
    },
  ]
  for (const r of rules) {
    await prisma.templateEligibilityRule.upsert({
      where: { id: r.id },
      update: { operator: r.operator, value: r.value },
      create: {
        id: r.id,
        templateId: templateId(1),
        attributeId: r.attributeId,
        operator: r.operator,
        value: r.value,
        description: r.description,
      },
    })
  }

  // --- The 12 trained templates ---------------------------------------------
  // Seeded rather than typed in by hand, because these are not sample data:
  // the classifier was measured against these exact Arabic documents and the
  // extractor against these exact questions. Everything here is idempotent, so
  // re-running the seed refreshes text without disturbing ids or live requests.
  // Urgent by definition, whoever asks and however they word it: a military
  // deferment misses a legal date, and somebody without an id card cannot sit an
  // exam or draw a salary. Everything else starts NORMAL -- a medical case or an
  // external deadline is a fact about one person, not about the request type, so
  // it is raised per request by staff holding request.act, with a reason.
  const URGENT_BY_DEFINITION = new Set(['MILITARY_DEFER', 'ID_REPLACEMENT'])

  // Fees, in SYP, charged on the first step of the templates that carry one --
  // the printed-document requests. These are demo figures: the institute sets
  // the real ones, and an administrator changes them on the workflow step
  // without touching the code. Every other step stays free, which is why this
  // patch cannot change what a live request costs.
  const FEE_BY_TEMPLATE: Record<string, number> = {
    ID_REPLACEMENT: 5000,
    TRANSCRIPT: 3000,
    ENROLL_CERT: 2000,
  }

  // Which fields a requester must supply before they are allowed to confirm.
  //
  // Kept here rather than in template_schema.json on purpose: that file is the
  // record of what the models were trained and measured on, and requiredness is
  // not a fact about the training data. It is institute policy about what a desk
  // cannot begin work without -- a transcript with no academic year named, or a
  // deferment with no recruitment division, is a request somebody has to send
  // back. Keeping the two apart means the export stays a faithful export and
  // this list stays editable without touching what the classifier was scored on.
  //
  // The extractor is never held to this list. It abstains rather than invents,
  // so a required field it could not find simply arrives empty and the requester
  // fills it in at the confirmation step -- the one moment the person who
  // actually knows the answer is in the loop. Only that step enforces this.
  //
  // One or two fields each, chosen as the ones a desk cannot proceed without.
  // Anything a clerk can ask for later, or that only shapes the output, is left
  // optional: `reason` is free text nobody blocks on, `copies` and `language`
  // have sane defaults, and `course_code` is recoverable from the course name.
  const REQUIRED_BY_TEMPLATE: Record<string, string[]> = {
    ADMIN_LEAVE: ['leave_type', 'start_date', 'days_count'],
    CHANGE_MAJOR: ['target_major'],
    CONFERENCE: ['conference_name', 'start_date'],
    ENROLL_CERT: ['purpose', 'destination_entity'],
    GRADE_APPEAL: ['course_name', 'exam_type'],
    ID_REPLACEMENT: ['loss_date'],
    MILITARY_DEFER: ['recruitment_division', 'deferment_year'],
    NO_OBJECTION: ['destination_entity', 'purpose', 'travel_date'],
    PROVISIONAL_GRAD: ['graduation_year', 'destination_entity'],
    SALARY_CERT: ['destination_entity'],
    STUDY_WITHDRAWAL: ['from_semester', 'duration_semesters'],
    TRANSCRIPT: ['academic_year', 'semester'],
  }

  const catalogue = loadCatalogue()
  let fieldRow = 2 // templateFieldId 1-2 belong to the demo template
  let ruleRow = 2 // eligibilityRuleId 1-2 likewise
  let stepRow = 0

  for (const [index, tpl] of catalogue.entries()) {
    const id = templateId(index + 2) // templateId(1) is the demo template
    const isStudent = tpl.requesterType === 'STUDENT'
    const title = { ar: tpl.nameAr, en: tpl.nameEn }
    const description = { ar: tpl.descriptionAr }

    await prisma.template.upsert({
      where: { id },
      update: {
        code: tpl.code,
        title,
        description,
        classifierDocument: tpl.classifierDocument,
        defaultPriority: URGENT_BY_DEFINITION.has(tpl.code)
          ? 'URGENT'
          : 'NORMAL',
      },
      create: {
        id,
        code: tpl.code,
        // Student paperwork is Academic; staff paperwork is Administrative.
        categoryId: isStudent ? categoryId(2) : categoryId(1),
        sensitivityLevelId: sensitivityId(2), // Internal
        title,
        description,
        classifierDocument: tpl.classifierDocument,
        defaultPriority: URGENT_BY_DEFINITION.has(tpl.code)
          ? 'URGENT'
          : 'NORMAL',
        isActive: true,
      },
    })

    // Fields. Requiredness comes from REQUIRED_BY_TEMPLATE above rather than
    // from the export, which marks everything optional because no field appears
    // in more than 90% of the training requests. That statistic is the right
    // answer for extraction and the wrong one for submission: the model must be
    // free to abstain on a field it cannot find, and the requester must not be
    // free to submit without it.
    const required = new Set(REQUIRED_BY_TEMPLATE[tpl.code] ?? [])
    for (const [ordinal, field] of tpl.fields.entries()) {
      fieldRow += 1
      const label = field.labelEn
        ? { ar: field.labelAr, en: field.labelEn }
        : { ar: field.labelAr }
      const stored = await prisma.templateField.upsert({
        where: { templateId_fieldKey: { templateId: id, fieldKey: field.key } },
        update: {
          label,
          dataType: field.type,
          isRequired: required.has(field.key),
          ordinal: ordinal + 1,
          extractionQuestion: field.extractionQuestion,
        },
        create: {
          id: templateFieldId(fieldRow),
          templateId: id,
          fieldKey: field.key,
          label,
          dataType: field.type,
          isRequired: required.has(field.key),
          ordinal: ordinal + 1,
          extractionQuestion: field.extractionQuestion,
        },
      })

      // ENUM options are stored by code (ANNUAL), which is what the extractor
      // returns and what validation checks; the Arabic label is display only.
      for (const [optionOrdinal, option] of (field.options ?? []).entries()) {
        await prisma.templateFieldOption.upsert({
          where: {
            templateFieldId_value: {
              templateFieldId: stored.id,
              value: option.code,
            },
          },
          update: { label: { ar: option.labelAr }, ordinal: optionOrdinal + 1 },
          create: {
            templateFieldId: stored.id,
            value: option.code,
            label: { ar: option.labelAr },
            ordinal: optionOrdinal + 1,
          },
        })
      }
    }

    // Who may request it, from the requester type the export already records.
    // This is the rule that made the user_type backfill below necessary.
    ruleRow += 1
    await prisma.templateEligibilityRule.upsert({
      where: { id: eligibilityRuleId(ruleRow) },
      update: {
        operator: 'IN',
        value: isStudent ? ['STUDENT', 'ADMIN'] : ['EMPLOYEE', 'ADMIN'],
      },
      create: {
        id: eligibilityRuleId(ruleRow),
        templateId: id,
        attributeId: attributeId(1), // user_type
        operator: 'IN',
        value: isStudent ? ['STUDENT', 'ADMIN'] : ['EMPLOYEE', 'ADMIN'],
        description: isStudent
          ? t('الطلاب والإداريون', 'Students and administrators')
          : t('الموظفون والإداريون', 'Employees and administrators'),
      },
    })

    // A workflow path per template, in one of two shapes. A path carries a
    // template id, so two shared paths are not possible -- these are twelve
    // paths cut from two patterns: review, then approval.
    const pathId = workflowPathId(index + 1)
    await prisma.workflowPath.upsert({
      where: { id: pathId },
      update: {},
      create: {
        id: pathId,
        templateId: id,
        name: isStudent
          ? t('مسار طلبات الطلاب', 'Student track')
          : t('مسار طلبات الموظفين', 'Employee track'),
        isActive: true,
      },
    })

    // Both steps are assigned by role. A production employee track would route
    // its first step to REQUESTER_DEPARTMENT_HEAD instead, but that resolves to
    // nobody until departments and their heads are synced, which would leave
    // every seeded employee request sitting unassigned.
    // The fee, if this template charges one, is attached to the first step: the
    // requester pays before the paperwork is worked on, not after it is signed.
    const fee: number | undefined = FEE_BY_TEMPLATE[tpl.code]

    const steps = isStudent
      ? [
          {
            name: t('تدقيق شؤون الطلاب', 'Student affairs review'),
            roleId: roleId(2),
            slaHours: 24,
            feeAmount: fee,
            actions: [actionTypeId(1), actionTypeId(2), actionTypeId(4)],
          },
          {
            name: t('الاعتماد', 'Approval'),
            roleId: roleId(1),
            slaHours: 48,
            feeAmount: undefined as number | undefined,
            actions: [actionTypeId(1), actionTypeId(2), actionTypeId(5)],
          },
        ]
      : [
          {
            name: t('تدقيق الموارد البشرية', 'HR review'),
            roleId: roleId(2),
            slaHours: 24,
            feeAmount: fee,
            actions: [actionTypeId(1), actionTypeId(2), actionTypeId(4)],
          },
          {
            name: t('اعتماد الإدارة', 'Management approval'),
            roleId: roleId(1),
            slaHours: 72,
            feeAmount: undefined as number | undefined,
            actions: [actionTypeId(1), actionTypeId(2), actionTypeId(5)],
          },
        ]

    let previousStepId: string | undefined
    for (const step of steps) {
      stepRow += 1
      const stepId = workflowStepId(stepRow)
      await prisma.workflowStep.upsert({
        where: { id: stepId },
        update: {
          // Re-seeding refreshes the fee on an existing database. Everything
          // else about a step is left alone: an administrator may have edited
          // the routing or the SLA, and the seed is not entitled to undo that.
          feeAmount: step.feeAmount ?? null,
          feeCurrency: step.feeAmount ? 'SYP' : null,
        },
        create: {
          id: stepId,
          workflowPathId: pathId,
          name: step.name,
          assigneeType: 'SPECIFIC_ROLE',
          assigneeRoleId: step.roleId,
          slaHours: step.slaHours,
          pausesSla: false,
          feeAmount: step.feeAmount ?? null,
          feeCurrency: step.feeAmount ? 'SYP' : null,
        },
      })
      for (const allowed of step.actions) {
        await prisma.workflowStepAllowedAction.upsert({
          where: {
            workflowStepId_actionTypeId: {
              workflowStepId: stepId,
              actionTypeId: allowed,
            },
          },
          update: {},
          create: { workflowStepId: stepId, actionTypeId: allowed },
        })
      }
      // Approval waits for review; without the edge both steps open at once.
      if (previousStepId)
        await prisma.workflowStepDependency.upsert({
          where: {
            workflowStepId_dependsOnStepId: {
              workflowStepId: stepId,
              dependsOnStepId: previousStepId,
            },
          },
          update: {},
          create: { workflowStepId: stepId, dependsOnStepId: previousStepId },
        })
      previousStepId = stepId
    }
  }

  // --- Backfill: every account gets its user_type attribute ------------------
  // Two things that look like one: users.user_type, which every account has,
  // and the user_type row in user_attributes, which is what the eligibility
  // engine actually reads. Only the admin ever had the second, so the rules
  // above would have denied everyone else -- the engine denies by default when
  // a rule names an attribute the user does not hold. New accounts now get it
  // written with the account; this fills in the ones that already exist.
  //
  // `update: {}` on purpose: a value an administrator set by hand outranks the
  // column. That is why the seeded admin keeps EMPLOYEE rather than ADMIN.
  const everyone = await prisma.user.findMany({
    select: { id: true, userType: true },
  })
  for (const person of everyone) {
    await prisma.userAttribute.upsert({
      where: {
        userId_attributeId: {
          userId: person.id,
          attributeId: attributeId(1),
        },
      },
      update: {},
      create: {
        userId: person.id,
        attributeId: attributeId(1),
        value: person.userType,
      },
    })
  }

  console.log(
    `  Catalogue    : ${catalogue.length} templates, ${fieldRow - 2} fields, ` +
      `${stepRow} workflow steps`,
  )
  console.log(`  user_type    : backfilled for ${everyone.length} accounts`)

  console.log('Seed complete.')
  console.log('  Admin login  : admin@correspondence.local / Admin@12345')
  console.log('  Reviewer 1   : reviewer1@correspondence.local / Review@12345')
  console.log('  Reviewer 2   : reviewer2@correspondence.local / Review@12345')
  console.log('  AI service   : ai-service@correspondence.local / change-me')
  console.log('')
  console.log('  Seeded ids (stable across resets):')
  console.log(`    SYSTEM account : ${SYSTEM_USER_ID}`)
  console.log(`    admin user     : ${userId(1)}`)
  console.log(`    reviewer 1     : ${userId(2)}`)
  console.log(`    reviewer 2     : ${userId(3)}`)
  console.log(`    Reviewer role  : ${roleId(2)}`)
  console.log(`    demo template  : ${templateId(1)}`)
  console.log(`    AI service user: ${userId(4)}`)
  console.log(`    first catalogue template: ${templateId(2)}`)
  console.log(`    action APPROVE : ${actionTypeId(1)}`)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (error) => {
    console.error(error)
    await prisma.$disconnect()
    process.exit(1)
  })
