services:
  postgres:
    image: postgres:16
    container_name: ics-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ics_admin
      POSTGRES_PASSWORD: ics_password
      POSTGRES_DB: correspondence
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: ics-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # web console
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata:
