export enum AssigneeType {
SPECIFIC_UNIT = "SPECIFIC_UNIT", SPECIFIC_ROLE = "SPECIFIC_ROLE",
REQUESTER_DEPARTMENT_HEAD = "REQUESTER_DEPARTMENT_HEAD", REQUESTER_FACULTY_DEAN = "REQUESTER_FACULTY_DEAN",
}