export enum CalendarPeriodType { EXAM = "EXAM", REGISTRATION 
= "REGISTRATION", HOLIDAY = "HOLIDAY", REGULAR = "REGULAR" }
export enum EventType {
STATUS_CHANGE = "STATUS_CHANGE", STEP_STARTED = "STEP_STARTED", STEP_COMPLETED = "STEP_COMPLETED",
ACTION_TAKEN = "ACTION_TAKEN", ASSIGNED = "ASSIGNED",
}
export enum ModelType { NLP_CLASSIFIER = "NLP_CLASSIFIER", 
    LSTM_REMAINING_TIME = "LSTM_REMAINING_TIME" }